# Generated by Django 3.0.8 on 2020-07-14 00:00

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the book's natural language", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_manuscript', models.FileField(upload_to=myapp.models.get_review_manuscript_full_path)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to=myapp.models.generate_filename)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('publication_date', models.DateField()),
                ('fk_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Author')),
                ('fk_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Genre')),
                ('fk_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Language')),
                ('fk_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Publisher')),
            ],
        ),
    ]
