# Generated by Django 3.0.8 on 2020-08-16 00:12

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200810_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Prezintation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_manuscript', models.FileField(upload_to=myapp.models.get_review_manuscript_full_path)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('tema_number', models.CharField(max_length=10)),
                ('publication_date', models.DateField()),
                ('fk_kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Kafedra')),
                ('fk_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Language')),
                ('fk_predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Predmet')),
                ('fk_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_manuscript', models.FileField(upload_to=myapp.models.get_review_manuscript_full_path)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('tema_number', models.CharField(max_length=10)),
                ('publication_date', models.DateField()),
                ('fk_kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Kafedra')),
                ('fk_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Language')),
                ('fk_predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Predmet')),
                ('fk_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher')),
            ],
        ),
    ]
