# Generated by Django 3.0.8 on 2020-08-17 10:08

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_kafedra_lection_predmet_prezintation_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_manuscript', models.FileField(upload_to=myapp.models.get_review_manuscript_full_path)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('tema_number', models.CharField(max_length=10)),
                ('publication_date', models.DateField()),
                ('fk_kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Kafedra')),
                ('fk_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Language')),
                ('fk_predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Predmet')),
                ('fk_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher')),
            ],
        ),
    ]
